# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'business-chat-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for business-chat-app
	
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Messaging'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'SDWebImage'
	pod 'Kingfisher'
	pod 'LetterAvatarKit'
  	pod 'CryptoSwift'
  	pod 'SVProgressHUD'
    pod 'Alamofire'
    pod 'SimpleImageViewer'

end

